/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { RoleManager, RoleManagerInterface } from "../RoleManager";

const _abi = [
  {
    inputs: [],
    name: "Auth",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "userRoles",
    outputs: [
      {
        internalType: "enum RoleManager.UserRole",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class RoleManager__factory {
  static readonly abi = _abi;
  static createInterface(): RoleManagerInterface {
    return new Interface(_abi) as RoleManagerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): RoleManager {
    return new Contract(address, _abi, runner) as unknown as RoleManager;
  }
}
