/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Dfreelancer } from "./Dfreelancer";
export type { EmployerLogic } from "./EmployerLogic";
export type { FreelancerLogic } from "./FreelancerLogic";
export type { JobLogic } from "./JobLogic";
export type { Proxy } from "./Proxy";
export type { Storage } from "./Storage";
