/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Storage {
  export type JobStruct = {
    id: BigNumberish;
    employer: AddressLike;
    title: string;
    description: string;
    budget: BigNumberish;
    completed: boolean;
    applicants: AddressLike[];
    hiredFreelancer: AddressLike;
  };

  export type JobStructOutput = [
    id: bigint,
    employer: string,
    title: string,
    description: string,
    budget: bigint,
    completed: boolean,
    applicants: string[],
    hiredFreelancer: string
  ] & {
    id: bigint;
    employer: string;
    title: string;
    description: string;
    budget: bigint;
    completed: boolean;
    applicants: string[];
    hiredFreelancer: string;
  };
}

export interface JobLogicInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allFreelancerAddresses"
      | "allJobs"
      | "applyForJob"
      | "completeJob"
      | "employers"
      | "escrowFunds"
      | "freelancers"
      | "getJobByID"
      | "hireFreelancer"
      | "jobs"
      | "owner"
      | "roles"
      | "totalCompletedJobs"
      | "totalEmployers"
      | "totalFreelancers"
      | "totalJobs"
      | "walletToUser"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AppliedForJob" | "JobCompleted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allFreelancerAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "allJobs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "applyForJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeJob",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "employers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowFunds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "freelancers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobByID",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hireFreelancer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "roles", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "totalCompletedJobs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalEmployers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFreelancers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "totalJobs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "walletToUser",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allFreelancerAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allJobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "applyForJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "employers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "escrowFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freelancers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJobByID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hireFreelancer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "roles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalCompletedJobs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEmployers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFreelancers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalJobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "walletToUser",
    data: BytesLike
  ): Result;
}

export namespace AppliedForJobEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    employer: AddressLike,
    freelancer: AddressLike
  ];
  export type OutputTuple = [
    jobId: bigint,
    employer: string,
    freelancer: string
  ];
  export interface OutputObject {
    jobId: bigint;
    employer: string;
    freelancer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCompletedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    freelancer: AddressLike,
    payment: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    freelancer: string,
    payment: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    freelancer: string;
    payment: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface JobLogic extends BaseContract {
  connect(runner?: ContractRunner | null): JobLogic;
  waitForDeployment(): Promise<this>;

  interface: JobLogicInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allFreelancerAddresses: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  allJobs: TypedContractMethod<[], [Storage.JobStructOutput[]], "view">;

  applyForJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  completeJob: TypedContractMethod<
    [jobId: BigNumberish, freelancerAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  employers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, string, string, boolean, bigint] & {
        employerAddress: string;
        name: string;
        industry: string;
        balance: bigint;
        country: string;
        image: string;
        registered: boolean;
        registration_date: bigint;
      }
    ],
    "view"
  >;

  escrowFunds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  freelancers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        freelancerAddress: string;
        name: string;
        skills: string;
        balance: bigint;
        country: string;
        gigTitle: string;
        gitDescription: string;
        jobsCompleted: bigint;
        registered: boolean;
        registration_date: bigint;
        starting_price: bigint;
      }
    ],
    "view"
  >;

  getJobByID: TypedContractMethod<
    [jobId: BigNumberish],
    [Storage.JobStructOutput],
    "view"
  >;

  hireFreelancer: TypedContractMethod<
    [jobId: BigNumberish, freelancerAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, boolean, string] & {
        id: bigint;
        employer: string;
        title: string;
        description: string;
        budget: bigint;
        completed: boolean;
        hiredFreelancer: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  roles: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalCompletedJobs: TypedContractMethod<[], [bigint], "view">;

  totalEmployers: TypedContractMethod<[], [bigint], "view">;

  totalFreelancers: TypedContractMethod<[], [bigint], "view">;

  totalJobs: TypedContractMethod<[], [bigint], "view">;

  walletToUser: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allFreelancerAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "allJobs"
  ): TypedContractMethod<[], [Storage.JobStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "applyForJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeJob"
  ): TypedContractMethod<
    [jobId: BigNumberish, freelancerAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "employers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, string, string, boolean, bigint] & {
        employerAddress: string;
        name: string;
        industry: string;
        balance: bigint;
        country: string;
        image: string;
        registered: boolean;
        registration_date: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "escrowFunds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "freelancers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        freelancerAddress: string;
        name: string;
        skills: string;
        balance: bigint;
        country: string;
        gigTitle: string;
        gitDescription: string;
        jobsCompleted: bigint;
        registered: boolean;
        registration_date: bigint;
        starting_price: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobByID"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [Storage.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hireFreelancer"
  ): TypedContractMethod<
    [jobId: BigNumberish, freelancerAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, boolean, string] & {
        id: bigint;
        employer: string;
        title: string;
        description: string;
        budget: bigint;
        completed: boolean;
        hiredFreelancer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "roles"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalCompletedJobs"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalEmployers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFreelancers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalJobs"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "walletToUser"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "AppliedForJob"
  ): TypedContractEvent<
    AppliedForJobEvent.InputTuple,
    AppliedForJobEvent.OutputTuple,
    AppliedForJobEvent.OutputObject
  >;
  getEvent(
    key: "JobCompleted"
  ): TypedContractEvent<
    JobCompletedEvent.InputTuple,
    JobCompletedEvent.OutputTuple,
    JobCompletedEvent.OutputObject
  >;

  filters: {
    "AppliedForJob(uint256,address,address)": TypedContractEvent<
      AppliedForJobEvent.InputTuple,
      AppliedForJobEvent.OutputTuple,
      AppliedForJobEvent.OutputObject
    >;
    AppliedForJob: TypedContractEvent<
      AppliedForJobEvent.InputTuple,
      AppliedForJobEvent.OutputTuple,
      AppliedForJobEvent.OutputObject
    >;

    "JobCompleted(uint256,address,uint256)": TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
    JobCompleted: TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
  };
}
