/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Employers",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Employers__factory>;
    getContractFactory(
      name: "Dfreelancer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Dfreelancer__factory>;
    getContractFactory(
      name: "Djob",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Djob__factory>;
    getContractFactory(
      name: "RoleManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RoleManager__factory>;

    getContractAt(
      name: "Employers",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Employers>;
    getContractAt(
      name: "Dfreelancer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Dfreelancer>;
    getContractAt(
      name: "Djob",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Djob>;
    getContractAt(
      name: "RoleManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RoleManager>;

    deployContract(
      name: "Employers",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Employers>;
    deployContract(
      name: "Dfreelancer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Dfreelancer>;
    deployContract(
      name: "Djob",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Djob>;
    deployContract(
      name: "RoleManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RoleManager>;

    deployContract(
      name: "Employers",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Employers>;
    deployContract(
      name: "Dfreelancer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Dfreelancer>;
    deployContract(
      name: "Djob",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Djob>;
    deployContract(
      name: "RoleManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RoleManager>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
