/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "Dfreelancer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Dfreelancer__factory>;
    getContractFactory(
      name: "EmployerLogic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EmployerLogic__factory>;
    getContractFactory(
      name: "FreelancerLogic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FreelancerLogic__factory>;
    getContractFactory(
      name: "JobLogic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.JobLogic__factory>;
    getContractFactory(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxy__factory>;
    getContractFactory(
      name: "Storage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Storage__factory>;

    getContractAt(
      name: "Initializable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "Dfreelancer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Dfreelancer>;
    getContractAt(
      name: "EmployerLogic",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EmployerLogic>;
    getContractAt(
      name: "FreelancerLogic",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FreelancerLogic>;
    getContractAt(
      name: "JobLogic",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.JobLogic>;
    getContractAt(
      name: "Proxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxy>;
    getContractAt(
      name: "Storage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Storage>;

    deployContract(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "Dfreelancer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Dfreelancer>;
    deployContract(
      name: "EmployerLogic",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmployerLogic>;
    deployContract(
      name: "FreelancerLogic",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FreelancerLogic>;
    deployContract(
      name: "JobLogic",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.JobLogic>;
    deployContract(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Proxy>;
    deployContract(
      name: "Storage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Storage>;

    deployContract(
      name: "Initializable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "Dfreelancer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Dfreelancer>;
    deployContract(
      name: "EmployerLogic",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmployerLogic>;
    deployContract(
      name: "FreelancerLogic",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FreelancerLogic>;
    deployContract(
      name: "JobLogic",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.JobLogic>;
    deployContract(
      name: "Proxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Proxy>;
    deployContract(
      name: "Storage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Storage>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
